service: 
  proweb:
    build: .
    depends_on:
      - db
    ports: 
      -"4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
  
  prodb:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db


